name: Wii CI

on: [push, pull_request]

jobs:
  wii:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container: ghcr.io/extremscorner/libogc2:latest
 
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        catnip build wii
